name: Build and Deploy Code

on: [push,pull_request]

jobs:
  job1: 
    runs-on: windows-2022
    steps:
      - name: pulling git repo
        uses: actions/checkout@v2
      - name: say hi to sanjeev
        run: echo "hello sanjeev"
  




